# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/whsol/dlist/models/category/columns.yaml

# Model Class name
modelClass: WhSol\DList\Models\Category

# List Title
title: Manage Categories

# Link URL for each record
recordUrl: whsol/dlist/categories/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 5

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



